### ISSUE TITLE
Support ALLOW_UNQUOTED_FIELD_NAMES option

### ISSUE THREAD

**Issue by y-ken** [hiroyuki-sato/embulk-parser-jsonpath#5]
I have faced a trouble with non standard json format.
To solve the problem it may need to add `ALLOW_UNQUOTED_FIELD_NAMES` flag support.
cf. https://www.mkyong.com/java/jackson-was-expecting-double-quote-to-start-field-name/

* The error message:
`Unexpected character ('u' (code 117)): was expecting double-quote to start field name`

* The record sample: 
`{uid=20170116-22621628, date=2017-01-16 00:22:44 +0900, url=https://www.example.co.jp.....snip}`

**Comment by y-ken** [comment]
Here is the stack trace.

```
org.embulk.exec.PartialExecutionException: org.embulk.spi.json.JsonParseException: Failed to parse JSON: {uid=20170116-22621624, date=2017-01-16 00:22:43 +0900, url=https://www.example.co.jp/foo/bar...
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
	at RUBY.run(/usr/local/bin/embulk!/embulk/runner.rb:84)
	at RUBY.run(/usr/local/bin/embulk!/embulk/command/embulk_run.rb:307)
	at RUBY.<main>(/usr/local/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(usr/local/bin/embulk/embulk/command/file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.<main>(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
	at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
	at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
	at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
	at org.jruby.Main.internalRun(org/jruby/Main.java:313)
	at org.jruby.Main.run(org/jruby/Main.java:242)
	at org.jruby.Main.main(org/jruby/Main.java:204)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: org.embulk.spi.json.JsonParseException: Failed to parse JSON: {uid=20170116-22621624, date=2017-01-16 00:22:43 +0900, url=https://www.example.co.jp/foo/bar...
	at org.embulk.spi.json.JsonParser$AbstractParseContext.next(org/embulk/spi/json/JsonParser.java:154)
	at org.embulk.spi.json.JsonParser$SingleParseContext.parse(org/embulk/spi/json/JsonParser.java:115)
	at org.embulk.spi.json.JsonParser.parse(org/embulk/spi/json/JsonParser.java:41)
	at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(org/embulk/parser/jsonpath/JsonpathParserPlugin.java:99)
	at org.embulk.spi.FileInputRunner.run(org/embulk/spi/FileInputRunner.java:153)
	at org.embulk.spi.util.Executors.process(org/embulk/spi/util/Executors.java:67)
	at org.embulk.spi.util.Executors.process(org/embulk/spi/util/Executors.java:42)
	at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(org/embulk/exec/LocalExecutorPlugin.java:184)
	at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(org/embulk/exec/LocalExecutorPlugin.java:180)
	at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(java/lang/Thread.java:745)
	Suppressed: org.embulk.spi.json.JsonParseException: Failed to parse JSON: {uid=20170116-22621628, date=2017-01-16 00:22:44 +0900, url=https://www.example.co.jp/foo/bar...
		at org.embulk.spi.json.JsonParser$AbstractParseContext.next(JsonParser.java:154)
		at org.embulk.spi.json.JsonParser$SingleParseContext.parse(JsonParser.java:115)
		at org.embulk.spi.json.JsonParser.parse(JsonParser.java:41)
		at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:99)
		at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:153)
		at org.embulk.spi.util.Executors.process(Executors.java:67)
		at org.embulk.spi.util.Executors.process(Executors.java:42)
		at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:184)
		at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:180)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('u' (code 117)): was expecting double-quote to start field name
```

**Comment by hiroyuki-sato** [comment]
I think This is **not** JSON data. 

```
{uid=20170116-22621628, date=2017-01-16 00:22:44 +0900, url=https://www.example.co.jp.....snip}
```

* name field isn't quoted. (You mentioned)

Additionally.

* Data field isn't also quoted. 
* name and value separator use `=` instead of `:`.

That's why I think the `ALLOW_UNQUOTED_FIELD_NAMES` option can't solve all of the problems. 

## About internal implementation.

Internally, I just call the class `org.embulk.spi.json.JsonParser`.
https://github.com/hiroyuki-sato/embulk-parser-jsonpath/blob/master/src/main/java/org/embulk/parser/jsonpath/JsonpathParserPlugin.java#L99
So We need to modify that class. 

Unfortunately, 
this class doesn't maintain by this project. 

## Alternative solution 

Have you ever tried [embulk-parser-regex](https://github.com/mokemokechicken/embulk-parser-regex)?

```
regex '{uid=(?<uid>[^,]+)\s+date=(?<date>[^,]+)\s+url=(?<url>[^,]+)}'
```

This plugin may work well if data entry orders are completely same.

**Comment by hiroyuki-sato** [comment]
He said that. `{name=value}` is the just log file only. 
The input data is valid. He validated the data with another tool.
[Twitter](https://twitter.com/yoshi_ken/status/836235225730437120) (Japanese text).

**Comment by y-ken** [comment]
I checked that JSON are not corrupted and valid JSON.
`{"uid":"20170116-22621638","date":"2017-01-16 00:22:46 +0900"}`

This problem is that. therefore, it is not necessary to support `ALLOW_UNQUOTED_FIELD_NAMES`

* "root: "$" cause error
`Parse failed reason = Failed to parse JSON: {uid=20170116-22621638, date=2017-01-16 00:22:46 +0900,.....`

* "root: $." cannot use with this error
`Error: com.jayway.jsonpath.InvalidPathException: Path must not end with a '.' or '..'`

**Comment by takumakanari** [comment]
Hi @y-ken, 
curretly, some new features have added in v0.2.0. 
Does it solve your problem?
